(function(){
"use strict";
let products=[];
const $=id=>document.getElementById(id);
async function apiRequest(url,options={}){const response=await DripAPI.fetch(url,{credentials:"include",headers:{"Content-Type":"application/json",...(options.headers||{})},...options});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"Request failed.");return data;}
document.addEventListener("DOMContentLoaded",()=>setupAdminAuth());
async function setupAdminAuth(){const auth=$("adminAuth");if(!auth)return;const setupForm=$("adminSetupForm"),loginForm=$("adminLoginForm"),title=$("adminAuthTitle"),desc=$("adminAuthDescription"),error=$("adminAuthError");const showError=m=>error.textContent=m;try{await apiRequest("/api/admin/me");authorize(auth);return;}catch{}let status;try{status=await apiRequest("/api/admin/status");}catch{showError("Secure backend is not reachable. Start the DripCartel server.");return;}if(!status.configured){title.innerHTML='Create <span>administrator.</span>';desc.textContent="Secure first-run bootstrap. The production server should require the ADMIN_SETUP_TOKEN.";setupForm.hidden=false;setupForm.addEventListener("submit",async e=>{e.preventDefault();showError("");const email=$("adminSetupEmail").value.trim(),password=$("adminSetupPassword").value,confirm=$("adminSetupPasswordConfirm").value;if(password!==confirm)return showError("Passwords do not match.");const headers={};const token=$("adminSetupToken")?.value.trim();if(token)headers["x-admin-setup-token"]=token;try{await apiRequest("/api/admin/setup",{method:"POST",headers,body:JSON.stringify({email,password})});authorize(auth);await renderAdmin();}catch(err){showError(err.message);}});}else{title.innerHTML='Admin <span>login.</span>';desc.textContent="Sign in to the protected administrator account.";loginForm.hidden=false;loginForm.addEventListener("submit",async e=>{e.preventDefault();showError("");try{await apiRequest("/api/admin/login",{method:"POST",body:JSON.stringify({email:$("adminEmail").value.trim(),password:$("adminPassword").value})});authorize(auth);await renderAdmin();}catch(err){showError(err.message);$("adminPassword").value="";$("adminPassword").focus();}});}}
function authorize(auth){document.body.classList.add("admin-authorized");auth.remove();bindAdminUI();applyTheme();setupTheme();setupTransitions();navigate();}
function bindAdminUI(){document.querySelectorAll(".admin-link[data-section]").forEach(a=>a.addEventListener("click",()=>showSection(a.dataset.section)));$("adminMenuBtn")?.addEventListener("click",()=>$('adminSidebar').classList.toggle('open'));$("adminSearch")?.addEventListener("input",renderProducts);$("closeEditor")?.addEventListener("click",closeEditor);$("cancelEditor")?.addEventListener("click",closeEditor);$("productEditor")?.addEventListener("click",e=>{if(e.target.id==="productEditor")closeEditor();});$("productForm")?.addEventListener("submit",saveProduct);$("productImage")?.addEventListener("change",previewImage);document.querySelectorAll("[data-product-tab]").forEach(b=>b.addEventListener("click",()=>productTab(b.dataset.productTab,b)));document.querySelectorAll(".order-tabs .subtab").forEach(b=>b.addEventListener("click",()=>{document.querySelectorAll(".order-tabs .subtab").forEach(x=>x.classList.remove("active"));b.classList.add("active");filterOrders(b.textContent.trim());}));$("addProductDashboard")?.addEventListener("click",()=>openEditor());$("addProductCatalogue")?.addEventListener("click",()=>openEditor());$("manageInventoryBtn")?.addEventListener("click",()=>showSection("products"));$("logoutAdminBtn")?.addEventListener("click",logoutAdmin);$("saveShippingBtn")?.addEventListener("click",saveShippingSettings);$("saveSettingsBtn")?.addEventListener("click",saveShippingSettings);$("createDiscountBtn")?.addEventListener("click",()=>DripCommon.showToast("Discounts require a promotion table before activation."));}
function navigate(){showSection(location.hash.slice(1)||"dashboard");}window.addEventListener("hashchange",navigate);
function showSection(id){document.querySelectorAll(".admin-section").forEach(s=>s.classList.toggle("active-section",s.id===id));document.querySelectorAll(".admin-link").forEach(a=>a.classList.toggle("active",a.dataset.section===id));if($("sectionTitle"))$("sectionTitle").textContent=id.charAt(0).toUpperCase()+id.slice(1);if(id==="dashboard")renderMetrics();if(id==="orders")renderOrders();}
async function refreshProducts(){try{products=await apiRequest("/api/products").then(x=>Array.isArray(x)?x:x.products||[]);}catch{products=[];}}
async function renderAdmin(){await refreshProducts();await renderMetrics();await renderProducts();await renderOrders();renderLowStock();await loadSettings();}
async function renderMetrics(){try{const{metrics}=await apiRequest("/api/admin/metrics");$("kpiProducts").textContent=products.length;$("kpiOrders").textContent=metrics.orders;$("kpiRevenue").textContent=money(metrics.revenue);$("kpiCustomers").textContent=metrics.customers;const note=document.querySelector("#dashboard .admin-kpis");note?.querySelectorAll("small").forEach((x,i)=>{x.textContent=["Paid orders","All order statuses","Active accounts","Live catalogue"][i]||"";});const counts=metrics.statuses||{};const labels={pending_payment:"Pending",paid:"Paid",processing:"Processing",shipped:"Shipped",delivered:"Completed"};document.querySelectorAll("#dashboard .status-bars>div").forEach(row=>{const label=row.querySelector("span")?.textContent.trim();const status=Object.keys(labels).find(k=>labels[k]===label);const count=Number(counts[status]||0);const total=Math.max(1,Number(metrics.orders||0));const bar=row.querySelector("b");const num=row.querySelector("em");if(bar)bar.style.width=`${Math.min(100,Math.round(count/total*100))}%`;if(num)num.textContent=count;});}catch{}}
async function loadSettings(){try{const{settings}=await apiRequest("/api/admin/settings");if(!settings)return;$("standardShipping").value=settings.standardShipping;$("freeShippingThreshold").value=settings.freeShippingThreshold;$("storeCountry").value=settings.country||"ZA";$("storeName").value=settings.storeName||"DripCartel";$("storeTagline").value=settings.tagline||"";$("storeCurrency").value=settings.currency||"ZAR";$("storeStatus").value=settings.storeStatus||"open";}catch{}}
async function saveShippingSettings(){try{const payload={standardShipping:Number($("standardShipping").value),expressShipping:100,freeShippingThreshold:Number($("freeShippingThreshold").value),country:$("storeCountry").value||"ZA",storeName:$("storeName")?.value||"DripCartel",tagline:$("storeTagline")?.value||"Streetwear with attitude.",currency:$("storeCurrency")?.value||"ZAR",storeStatus:$("storeStatus")?.value||"open"};await apiRequest("/api/admin/settings",{method:"PATCH",body:JSON.stringify(payload)});DripCommon.showToast("Settings saved securely.");}catch(err){DripCommon.showToast(err.message);}}
async function renderProducts(){if(!$("adminProductRows"))return;const q=($("adminSearch")?.value||"").toLowerCase();const list=products.filter(p=>(p.name+" "+p.category).toLowerCase().includes(q));$("adminProductRows").innerHTML=list.map(p=>`<tr><td><div class="table-product"><div class="table-thumb">${productVisual(p)}</div><span>${escapeHTML(p.name)}</span></div></td><td>${escapeHTML(p.category)}</td><td><strong>${money(p.price)}</strong></td><td>${p.stock}</td><td><span class="status ${p.stock===0?"out":p.stock<5?"low":"live"}">${p.stock===0?"Sold out":p.stock<5?"Low stock":"Live"}</span></td><td><button class="table-action" type="button" data-edit-product="${escapeHTML(p.id)}">Edit</button><button class="table-action delete" type="button" data-delete-product="${escapeHTML(p.id)}">Delete</button></td></tr>`).join("");$("adminProductRows").querySelectorAll("[data-edit-product]").forEach(b=>b.addEventListener("click",()=>editProduct(b.dataset.editProduct)));$("adminProductRows").querySelectorAll("[data-delete-product]").forEach(b=>b.addEventListener("click",()=>deleteProduct(b.dataset.deleteProduct)));}
async function renderOrders(){if(!$("adminOrderRows"))return;try{const{orders}=await apiRequest("/api/admin/orders");$("adminOrderRows").innerHTML=orders.length?orders.map(o=>`<tr><td><strong>#${escapeHTML(o.orderNumber)}</strong></td><td>${escapeHTML(`${o.firstName||""} ${o.lastName||""}`.trim()||o.email)}</td><td>${escapeHTML(new Date(o.createdAt).toLocaleDateString("en-ZA"))}</td><td>${money(o.total)}</td><td><span class="status ${["paid","processing","shipped","delivered"].includes(o.status)?"live":o.status==="cancelled"?"out":"low"}">${escapeHTML(o.status.replaceAll("_"," "))}</span></td><td>${orderActionMarkup(o)}</td></tr>`).join(""):"<tr><td colspan=6>No orders yet.</td></tr>";$("adminOrderRows").querySelectorAll("[data-order-status]").forEach(b=>b.addEventListener("click",()=>changeOrderStatus(b.dataset.id,b.dataset.orderStatus)));}catch(err){$("adminOrderRows").innerHTML=`<tr><td colspan=6>${escapeHTML(err.message)}</td></tr>`;}}
function orderActionMarkup(o){const next=o.status==="paid"?"processing":o.status==="processing"?"shipped":o.status==="shipped"?"delivered":"";return next?`<button class="table-action" type="button" data-order-status="${next}" data-id="${escapeHTML(o.id)}">Mark ${next}</button>`:"—";}
async function changeOrderStatus(id,status){try{await apiRequest(`/api/admin/orders/${encodeURIComponent(id)}/status`,{method:"PATCH",body:JSON.stringify({status})});await renderOrders();await renderMetrics();DripCommon.showToast("Order updated.");}catch(err){DripCommon.showToast(err.message);}}
function filterOrders(filter){document.querySelectorAll("#adminOrderRows tr").forEach(row=>{const status=row.querySelector(".status")?.textContent.trim().toLowerCase()||"";const value=filter.toLowerCase();row.hidden=value!=="all"&&!status.includes(value);});}
function renderLowStock(){if(!$('lowStockList'))return;const low=products.filter(p=>p.stock<5);$('lowStockList').innerHTML=low.length?low.map(p=>`<div class="low-row"><span>${escapeHTML(p.name)}</span><b>${p.stock} left</b><button class="table-action" type="button" data-low-edit="${escapeHTML(p.id)}">Edit</button></div>`).join(""):"<div class=\"empty-admin\"><p>Inventory looks healthy. No low-stock items.</p></div>";$('lowStockList').querySelectorAll('[data-low-edit]').forEach(b=>b.addEventListener('click',()=>editProduct(b.dataset.lowEdit)));}
function productTab(tab,b){document.querySelectorAll('[data-product-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');if(tab!=="all")DripCommon.showToast(`${tab.charAt(0).toUpperCase()+tab.slice(1)} settings are managed through product records.`);}
let currentImage="";
function openEditor(p){currentImage="";$("productEditor").classList.add("open");$("editorTitle").textContent=p?"Edit Product":"Add Product";$("productId").value=p?.id||"";$("productName").value=p?.name||"";$("productCategory").value=p?.category||"T-Shirts";$("productPrice").value=p?.price??350;$("productStock").value=p?.stock??10;$("productSizes").value=Array.isArray(p?.sizes)?p.sizes.join(", "):p?.sizes||"S, M, L";$("productColours").value=Array.isArray(p?.colours)?p.colours.join(", "):p?.colours||"Black";$("productDescription").value=p?.description||"";currentImage=p?.image||"";$("imagePreview").innerHTML=currentImage?`<img src="${escapeHTML(currentImage)}" alt="">`:'<span>Product image preview</span>';}
function closeEditor(){$("productEditor").classList.remove("open");}
function previewImage(e){const f=e.target.files?.[0];if(!f)return;if(f.size>180*1024)return DripCommon.showToast("Product image must be 180 KB or smaller.");const r=new FileReader();r.onload=()=>{currentImage=r.result;$("imagePreview").innerHTML=`<img src="${escapeHTML(currentImage)}" alt="">`;};r.readAsDataURL(f);}
async function saveProduct(e){e.preventDefault();const id=$("productId").value||`product-${Date.now()}`;const existing=products.find(x=>x.id===id);const existingGallery=Array.isArray(existing?.gallery)?[...existing.gallery]:[];const gallery=currentImage?([currentImage,...existingGallery.filter((_,index)=>index>0)]):existingGallery;const item={id,name:$("productName").value.trim(),category:$("productCategory").value,price:Number($("productPrice").value),stock:Number($("productStock").value),sizes:$("productSizes").value.split(",").map(x=>x.trim()).filter(Boolean),colours:$("productColours").value.split(",").map(x=>x.trim()).filter(Boolean),description:$("productDescription").value.trim(),image:currentImage,gallery,badge:existing?.badge||""};try{const exists=Boolean(existing);await apiRequest(`/api/products/${encodeURIComponent(id)}`,{method:exists?"PATCH":"POST",body:JSON.stringify(item)});closeEditor();await renderAdmin();DripCommon.showToast("Product saved securely.");}catch(err){DripCommon.showToast(err.message);}}
function editProduct(id){const p=products.find(x=>x.id===id);if(p)openEditor(p);}
async function deleteProduct(id){const p=products.find(x=>x.id===id);if(!p||!window.confirm(`Delete ${p.name}?`))return;try{await apiRequest(`/api/products/${encodeURIComponent(id)}`,{method:"DELETE"});await renderAdmin();DripCommon.showToast("Product deleted.");}catch(err){DripCommon.showToast(err.message);}}
async function logoutAdmin(){try{await apiRequest('/api/admin/logout',{method:'POST'});}catch{}location.reload();}
})();
